#PostgresSql
spring.datasource.url: jdbc:postgresql://localhost/funnydb
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.generate-ddl: true

server.port: 8081

#clm-user-management-service.ribbon.listOfServers: localhost:8080
#ribbon.eureka.enabled=false

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.application.name: portal-content-service
spring.config.name: portal-content-service

# Discovery Server Access
eureka.client.serviceUrl.defaultZone: http://localhost:8888/eureka/
eureka.instance.leaseRenewalIntervalInSeconds: 5
eureka.instance.metadataMap.instanceId: ${spring.application.name}:${spring.application.instance_id:8081}